version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=elecciones
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db